In [1]:
import numpy as np

In [3]:
a = np.array([1,1,1])
a

array([1, 1, 1])

In [5]:
a = np.array([[1,1,1],[2,2,2]])
a

array([[1, 1, 1],
       [2, 2, 2]])

In [7]:
b = np.array([['a','b','c'],['d','e','f']])
b

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [9]:
c = np.array([(1,2,3),[4,5,6],(7,8,9)])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
d = np.array([[1,1,1],[2,2,2]],dtype = complex)
d

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [2.+0.j, 2.+0.j, 2.+0.j]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [21]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.random.random(4)

array([0.25586687, 0.16319498, 0.55586733, 0.71289354])

In [26]:
np.random.random((4,4))

array([[0.79728215, 0.16706501, 0.65361541, 0.68461272],
       [0.87297459, 0.17023284, 0.08556325, 0.44601014],
       [0.19934976, 0.92117563, 0.47216376, 0.93524437],
       [0.67034286, 0.20412017, 0.99451365, 0.92977773]])

In [29]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [30]:
a + 4

array([4, 5, 6, 7])

In [31]:
a * 2

array([0, 2, 4, 6])

In [33]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [34]:
a + b

array([ 4,  6,  8, 10])

In [35]:
a - b

array([-4, -4, -4, -4])

In [37]:
print(a,b)
a * b

[0 1 2 3] [4 5 6 7]


array([ 0,  5, 12, 21])

In [39]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [40]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [42]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [45]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [47]:
A = np.array([[15,24,46],[14,56,57],[72,43,64]])
A

array([[15, 24, 46],
       [14, 56, 57],
       [72, 43, 64]])

In [48]:
A.T

array([[15, 14, 72],
       [24, 56, 43],
       [46, 57, 64]])

In [50]:
A.transpose()
A

array([[15, 24, 46],
       [14, 56, 57],
       [72, 43, 64]])

In [51]:
np.trace(A)

np.int64(135)

In [52]:
np.linalg.inv(A)

array([[-0.01776057, -0.00692866,  0.01893625],
       [-0.05028765,  0.03686925,  0.00330757],
       [ 0.05376765, -0.01697678, -0.00790055]])

In [69]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [70]:
a += 1
a

array([1, 2, 3, 4])

In [71]:
a -= 1
a

array([0, 1, 2, 3])

In [72]:
a += 4
a

array([4, 5, 6, 7])

In [73]:
a *= 2
a

array([ 8, 10, 12, 14])

In [75]:
a = np.random.random(12)
a

array([0.49986416, 0.53104603, 0.23441446, 0.64372236, 0.9531607 ,
       0.30387555, 0.62874281, 0.47080317, 0.23688811, 0.92497939,
       0.61913845, 0.06533947])

In [77]:
A = a.reshape(3,4)
A

array([[0.49986416, 0.53104603, 0.23441446, 0.64372236],
       [0.9531607 , 0.30387555, 0.62874281, 0.47080317],
       [0.23688811, 0.92497939, 0.61913845, 0.06533947]])

In [79]:
a.shape = (3,4)
a

array([[0.49986416, 0.53104603, 0.23441446, 0.64372236],
       [0.9531607 , 0.30387555, 0.62874281, 0.47080317],
       [0.23688811, 0.92497939, 0.61913845, 0.06533947]])

In [80]:
a.ravel()

array([0.49986416, 0.53104603, 0.23441446, 0.64372236, 0.9531607 ,
       0.30387555, 0.62874281, 0.47080317, 0.23688811, 0.92497939,
       0.61913845, 0.06533947])

In [82]:
a.shape = (12)
a

array([0.49986416, 0.53104603, 0.23441446, 0.64372236, 0.9531607 ,
       0.30387555, 0.62874281, 0.47080317, 0.23688811, 0.92497939,
       0.61913845, 0.06533947])

In [83]:
A.transpose()

array([[0.49986416, 0.9531607 , 0.23688811],
       [0.53104603, 0.30387555, 0.92497939],
       [0.23441446, 0.62874281, 0.61913845],
       [0.64372236, 0.47080317, 0.06533947]])

In [85]:
A = np.ones((3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
B = np.zeros((3,3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [90]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [91]:
np.row_stack((a,b,c))

C:\Users\3090025W\AppData\Local\Temp\ipykernel_15216\3391918380.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b,c))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])