In [1]:
import numpy as np

In [3]:
a = np.array([1,1,1])
a

array([1, 1, 1])

In [5]:
a = np.array([[1,1,1],[2,2,2]])
a

array([[1, 1, 1],
       [2, 2, 2]])

In [7]:
b = np.array([['a','b','c'],['d','e','f']])
b

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [9]:
c = np.array([(1,2,3),[4,5,6],(7,8,9)])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
d = np.array([[1,1,1],[2,2,2]],dtype = complex)
d

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [2.+0.j, 2.+0.j, 2.+0.j]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [21]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.random.random(4)

array([0.25586687, 0.16319498, 0.55586733, 0.71289354])

In [26]:
np.random.random((4,4))

array([[0.79728215, 0.16706501, 0.65361541, 0.68461272],
       [0.87297459, 0.17023284, 0.08556325, 0.44601014],
       [0.19934976, 0.92117563, 0.47216376, 0.93524437],
       [0.67034286, 0.20412017, 0.99451365, 0.92977773]])

In [29]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [30]:
a + 4

array([4, 5, 6, 7])

In [31]:
a * 2

array([0, 2, 4, 6])

In [33]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [34]:
a + b

array([ 4,  6,  8, 10])

In [35]:
a - b

array([-4, -4, -4, -4])

In [37]:
print(a,b)
a * b

[0 1 2 3] [4 5 6 7]


array([ 0,  5, 12, 21])